- id: url:https://www.nature.com/articles/s41590-022-01311-1
  image: https://media.springernature.com/w440/springer-static/cover-hires/journal/41590/23/10
  tags:
    - neutrophils
    - myelopoiesis
    - gene regulation in immune cells
    
- id: doi:10.1126/scitranslmed.abl4106
  image: https://www.science.org/cms/asset/bdbf6c3c-9efd-434c-bece-d1a49c891933/stm.2022.14.issue-653.largecover.jpg
  tags:
    - glioblastoma
    - tumor microenvironment
    -     
    
- id: doi:10.1016/j.immuni.2022.05.009
  tags:
    - 
    
- id: doi:10.1084/jem.20211121
  tags:
    - 

- id: doi:10.1126/scitranslmed.abg8027
  tags:
    - 
    
- id: doi:10.1016/j.immuni.2021.05.016
  tags:
    - macrophages
    - myelopoiesis
    - gene regulation in immune cells

- id: doi:10.1016/j.celrep.2021.109143
  tags:
    - 
    
- id: doi:10.1038/s41467-021-22535-z
  tags:
    - 
   
- id: doi:10.1111/imr.12944
  tags:
    - neutrophils
    - myelopoiesis
    - gene regulation in immune cells
    
- id: doi:10.1016/j.cell.2020.10.003
  tags:
    - 

- id: doi:10.1038/s41586-019-1620-6
  tags:
    - 
    
- id: doi:10.1038/s41590-019-0399-9
  tags:
    - 
    
- id: doi:10.1038/s41577-019-0141-8
  tags:
    -    
    
- id: doi:10.1038/s41467-018-05315-0
  tags:
    -   
 
