- id: url:https://www.nature.com/articles/s41590-022-01311-1
  tags:
    - neutrophils
    - myelopoiesis
    - gene regulation in immune cells
    
- id: doi:10.1126/scitranslmed.abl4106
  tags:
    - neutrophils
    - myelopoiesis
    - gene regulation in immune cells    
    
- id: doi:10.1016/j.immuni.2022.05.009
  tags:
    - 
    
- id: doi:10.1084/jem.20211121
  tags:
    - 

- id: doi:10.1126/scitranslmed.abg8027
  tags:
    - 
    
- id: doi:10.1016/j.immuni.2021.05.016
  tags:
    - macrophages
    - myelopoiesis
    - gene regulation in immune cells

- id: doi:10.1016/j.celrep.2021.109143
  tags:
    - 
    
- id: doi:10.1038/s41467-021-22535-z
  tags:
    - 
   
- id: doi:10.1111/imr.12944
  tags:
    - neutrophils
    - myelopoiesis
    - gene regulation in immune cells
